drivers: gpu: msm: removed code which caused compile-time error
sakura/drivers/gpu/msm/adreno_debugfs.c:144:22: error: no member named 'fences' in 'struct event_fence_info'
                                sync_event->info.fences[i].name);
                                ~~~~~~~~~~~~~~~~ ^
1 error generated.